-- drop table if exists member CASCADE;
-- create table member(
--     id bigint generated by default as identity,
--     name varchar(255),
--     primary key (id)
-- );

create table User(
    id varchar(255) as identity ,
    car varchar(255),
    credit bigint,
    accu_credit bigint,
    rank bigint,
    primary key (id)
);

create table History(
    id varchar(255) as identity,
    src varchar(255),
    dest varchar(255),
    distance bigint,
    historyDate varchar(255),
    historyTime varchar(255),
    idx bigint,
    reward bigint,
    time bigint,
    primary key (id)
);

create table Location(
    id varchar(255) as identity,
    src varchar(255),
    dest varchar(255),
    primary key (id)
);
